### ISSUE TITLE
Potential missing forcats dependency

### ISSUE THREAD

**Issue by annakrystalli** [selcukorkmaz/MVN#1]
I just installed `MVN` and tried to run `mvn()` but got the following error:
```r
MVN::mvn(preds)
```
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘forcats’
```

Once I manually installed `forcats`, the function worked fine. I can't see `forcats` as a dependency in the `MVN` `DESCRIPTION` file so I just thought I'd let you know.

**Comment by selcukorkmaz** [comment]
Thanks for the valuable feedback.


On 28 Feb 2019, at 11:51, Anna Krystalli <notifications@github.com<mailto:notifications@github.com>> wrote:


I just installed MVN and tried to run mvn() but got the following error:

MVN::mvn(preds)

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘forcats’


Once I manually installed forcats, the function worked fine. I can't see forcats as a dependency in the MVN DESCRIPTION file so I just thought I'd let you know.
