### ISSUE TITLE
Package not loading in the R studio 

### ISSUE THREAD

**Issue by Pame266** [selcukorkmaz/MVN#4]
Hi,

After installing the MVN package, I am getting the below error on loading it. Can't figure the reason at the moment. This issue persists in both mac and windows. 
Thanks 

sROC 0.1-2 loaded
Error: package or namespace load failed for ‘MVN’:
 .onLoad failed in loadNamespace() for 'rjags', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rjags/libs/rjags.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rjags/libs/rjags.so, 10): Library not loaded: /usr/local/lib/libjags.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rjags/libs/rjags.so
  Reason: image not found

**Comment by Km233** [comment]
Hi Pame266, did you manage to resolve this yet? I have the same issue.

**Comment by selcukorkmaz** [comment]
Hi,

Please try to install the standalone JAGS and then retry to install the MVN.

https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/

**Comment by Km233** [comment]
> Hi,
> 
> Please try to install the standalone JAGS and then retry to install the MVN.
> 
> https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/

Thank you so much, issue fixed.

**Comment by Pame266** [comment]
Hi,
Sorry for the late reply. Yeah JAGS solved the installation issue and
thanks for the prompt response.

Regards

**Comment by davidbiol** [comment]
I had the same issue. https://stackoverflow.com/questions/38026485/icu-init-failed-u-file-access-error-when-running-swirl works for me.
